security:
  enable_authenticator_manager: true
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\SecurityAuthenticator
      logout:
        path: app_logout
        target: app_login

  access_control:
  # Define access controls, e.g., restricting routes to specific roles
  # - { path: ^/admin, roles: ROLE_ADMIN }

  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_STAFF, ROLE_CLIENT]
    ROLE_ADMIN: [ROLE_STAFF, ROLE_CLIENT, ROLE_PARTNER]
    ROLE_STAFF: [ROLE_USER]
    ROLE_PARTNER: [ROLE_USER]
    ROLE_USER: [ROLE_USER]

# Add any test-specific security configurations if needed
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10